### ISSUE TITLE
Renaming and Reservation Station

### ISSUE THREAD

**Issue by Sky-HChina** [openpower-cores/a2o#10]
I am a bit confused about the renaming and the RV module.
In the RV module, I found the related RV entry information listed below. However, I did not find the data information which should be included in the RV entry. In this case, how can the RV entry store the operand data and the temporary results? Or the A2O core implements the tomosula or other OoO techniques in a different way. Any related manuals are welcome.

`   assign rv0_instr_i0_dat = {
			      rv0_instr_i0_t1_v,
			      rv0_instr_i0_t1_t,
			      rv0_instr_i0_t2_v, 
			      rv0_instr_i0_t2_t,
			      rv0_instr_i0_t3_v,
			      rv0_instr_i0_t3_t,
			      rv0_instr_i0_s1_v,
			      rv0_instr_i0_s1_p,
			      rv0_instr_i0_s1_t,
			      rv0_instr_i0_s2_v,
			      rv0_instr_i0_s2_p,
			      rv0_instr_i0_s2_t,
			      rv0_instr_i0_s3_v, 
			      rv0_instr_i0_s3_p,
			      rv0_instr_i0_s3_t };

   assign rv0_instr_i0_dat_ex0 = {
				  rv0_instr_i0_instr, 
				  rv0_instr_i0_ifar,
				  rv0_instr_i0_ucode,
				  rv0_instr_i0_ucode_cnt,
				  rv0_instr_i0_t1_p,
				  rv0_instr_i0_t2_p, 
				  rv0_instr_i0_t3_p,
				  rv0_instr_i0_branch,
				  rv0_instr_i0_spare};`

**Comment by zhaoxiahust** [comment]
Based on my understanding, A2O exploits the rename module to map the architectural register to the physical register. In particular, the source architectural register will find its real physical register through the spec_map. The target architectural register will be assigned an available physical register.

RV does not store any data since the data is stored in the physical registers. RV is only used to store the instruction information such as the source physical register id so the instruction can be executed when its source data is ready. 

Completion buffer is used to guarantee the in-order commit or retirement. When the instruction is dispatched to the RV, it will have a dedicated entry in the completion buffer. If the instruction should not be executed or an exception happens, I guess the target physical registers of all wrong instructions will be disregarded. In other words, these physical registers will go back to the free physical register list and will be assigned to the architectural registers of the new coming instructions.

The above is my understanding of A2O. However, I am a bit confused about when an occupied physical register goes back to the free physical register list, which means it can be re-mapped. It seems to me that when an instruction commits /retires in the completion buffer, the current A2O implementation will free its target physical register immediately. This should not be the right case since the physical register might be the source of the later instructions. Until now, I did not find the related control logic in the A2O source code.

**Comment by openpowerwtf** [comment]
Thanks @zhaoxiahust, I think your explanation is correct.  The 'tag' info is passed around, but the actual regs reside in their functional units.
