### ISSUE TITLE
Why two dcache directories

### ISSUE THREAD

**Issue by Grubby-CPU** [openpower-cores/a2o#8]
In the source code of lq.v module, I find two entities of dcache directory in lq_ctl.v and lq_lsq.v, respectively. Why there are two entities? What's their purpose? Based on my understanding, there is usually one directory for one cache......

Thanks for your help!

**Comment by openpowerwtf** [comment]
I suspect they are functioning as a multi-read-port array (and multi-write?), implemented using physical 1R/1W arrays.  Need a good diagram of the lsq/ctl/dir* connections to the array ports.

**Comment by Grubby-CPU** [comment]
Good point. I think it might be better to locate these two directories into one module to make the functionality be clear:)))

**Comment by openpowerwtf** [comment]
Yes, I was thinking that too.  Typically they handled that within a component in the tri lib, so the ASIC array(s) could be selected that was most efficient.   Maybe the second one 'evolved' functionally (didn't exist at start, possibly because they started with A2I logic which had no store queue) and the logic never got combined, or they were kept separate to help physical design in some way.  No way to know now 🤪.
